apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx
  labels:
    app.kubernetes.io/name: nginx
    helm.sh/chart: nginx-1.3.5
    app.kubernetes.io/instance: example
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: example
    spec:
      initContainers:
      containers:
        # highlight-start
        - name: data-container
          image: redhat/granite-3-1b-a400m-instruct:1.0
          command:
            - sleep
            - infinity
          env:
            - name: IS_DATA_CONTAINER
              value: "true"
          lifecycle:
            postStart:
              exec:
                command:
                  - "echo"
        # highlight-end
        - name: nginx
          image: "nginx:1.18.0-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 6
          resources: {}
          volumeMounts:
          # highlight-start
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          command:
            - sh
            - -c
            - |2
              dataContainerPid=$(grep -a -l IS_DATA_CONTAINER=true /proc/*/environ 2>/dev/null | awk -F/ '{print $3}')

              echo "Data Container PID: $dataContainerPid"

              source="/proc/$dataContainerPid/root/models"
              target="/mnt/models"

              mkdir -p $(dirname "$target")
              ln -s "$source" "$target"

              echo "Linked $source to $target"

              echo "Listing files in /mnt/models/"
              ls -alh /mnt/models/

              nginx -g 'daemon off;'
          # highlight-end
      volumes:
        - name: html
          emptyDir: {}
      shareProcessNamespace: true
