name: build
on:
  push:
    branches:
      - "master"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Build
        run: |
          curl -L -o anemos.tar.gz https://github.com/ohayocorp/anemos/releases/latest/download/anemos-linux-amd64.tar.gz && \
          tar -xzf anemos.tar.gz && \
          rm anemos.tar.gz && \
          chmod +x anemos && \
          sudo mv anemos /usr/local/bin/

          bash build-docs-project.sh

          cd docs
          npm install
          npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_PAGES_ACCOUNT_ID }}
          command: pages deploy docs/build --project-name=anemos-docs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}